#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Mar 18 14:17:00 2022

@author: rdevinen
"""
# https://www.youtube.com/watch?v=GB9ByFAIAH4

import numpy as np

#%%


a = np.array([1,2,3])
b = np.array([[4,5,6,4,5,87,2,56,6,4,6,4,6,4,6,4,64,6,86,56,86,53,4], [4,5,6,4,5,87,2,56,6,4,6,4,6,4,6,4,64,6,86,56,86,53,4]], dtype="int64")


c = np.array([[[1,2],[3,4]], [[5,6], [7,8]]])



x = np.full((10,10,10), 55)


y = np.random.rand(4,2)

a = np.arange(10)

b = np.where(a < 5, x, 10*a)

#%%
